### ISSUE TITLE
[Bug]: adding features to annotation setting

### ISSUE THREAD

**Issue by megasser** [Arborator/arborator-frontend#357]
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

The list of default morphological features is incomplete (and our project uses some non-standard features), but when I add a feature to the JSON in the Project Settings file, save, close the file, and then reopen it, the new features are not there, and they don't take effect in the annotations (they are not displayed in the GUI and are not saved as "feats" (position 6) but rather as "misc" (position 10) in the CoNNL-U representation for sentences).

### Steps To Reproduce

1. Open Settings file for project ("Modify project settings").
2. Add new features under "FEATS" in "Annotation settings":
 {
    "name": "AccGen",
    "values": [
	"Fem",
	"Masc"
	]
      },
3. Click "Save annotation settings". See message "New annotation settings saved on the server."
4. Close Settings window.
5. Open Settings window. New features are missing.

### Project name

EETB Project: Amharic

### What browsers are you seeing the problem on?

Firefox

**Comment by khansadaoudi** [comment]
Hello @megasser, I can't reproduce your issue the new feature is succefully added and saved in the 6th column. I have checked your project the feature appears in the feats dialog
![Capture d’écran du 2024-03-07 13-41-48](https://github.com/Arborator/arborator-frontend/assets/50585493/289e3215-20d6-4cb1-b041-2040396d2a31)

**Comment by megasser** [comment]
Thank you. You're right; the feature does appear in that dialog, though it's still not visible in the saved Settings for the project, so there is no record of what has been changed there.

The problem is that we use a morphological analyzer to generate the features (as well as POS and LEMMA), so these features are already present in the CoNLL-U files that we upload to Arborator. We're only adding the relations. But when we save the annotated files from Arborator, features like AccGen end up in column 10 ('misc'). There are about 20 such features that we use, in addition to AccGen.

For example, see the attached screenshot for a sentence where AccGen should appear under a token (id 4: ኣት) but doesn't. In the saved CoNLL-U for this sentence, it appears in column 10, with other features that haven't been added to the settings.

# user_id = megasser
# timestamp = 1709756189174
# text = አስቴር ራባት ።
# sent_id = am_ref_6
1     አስቴር  አስቴር  PROPN PROPN Number=Sing 2     expl  _     _
2-4   ራባት   _     _     _     _     _     _     _     _
2     ራብ    ራበ    VERB  VERB  Aspect=Perf 0     root  _     _
3     አ     አ     PRON  PRON  Gender=Masc|Number=Sing|Person=3    2     nsubj _     _
4     ኣት    ኣት    PRON  PRON  _     2     obj   _     AccGen=Fem|AccNum=Sing|AccPers=3
5     ።     ።     PUNCT PUNCT _     2     punct _     _

Here's the CoNNL-U for this sentence that I uploaded originally, with the features, POS tags and lemmas already assigned. AccGen is in column 6 for token 4.

# text = አስቴር ራባት ።
# sent_id = am_ref_6
1     አስቴር  አስቴር  PROPN PROPN Number=Sing 1     _     _     _
2-4   ራባት   _     _     _     _     _     _     _     _
2     ራብ    ራበ    VERB  VERB  Aspect=Perf 2     _     _     _
3     አ     አ     PRON  PRON  Gender=Masc|Number=Sing|Person=3    2     nsubj _     _
4     ኣት    ኣት    PRON  PRON  AccGen=Fem|AccNum=Sing|AccPers=3    2     obj   _     _
5     ።     ።     PUNCT PUNCT _     5     _     _     _

Perhaps this a problem peculiar to our particular annotation protocol and so not worth your time, in which case I'll just write a script to move the features from column 10 to 6 whenever they're there in a saved sentence.

Thanks again for your help.
Michael

**Comment by megasser** [comment]
Hello again. I've tried to understand what's going on, and I'm totally mystified. Sometimes new features go in the right column (6), sometimes in the wrong column (10). And sometimes a feature that was in column 6 has moved later to column 10, when I have done nothing in between other than close and re-open the file.

Sometimes a feature that was previously saved and showed up in the Universal Features dialog for a project  (as you showed in your screenshot) now no longer shows up there.

And when I save new features in EETB: Amharic, they fail to show up later in the JSON in Settings, but they do show up in the Settings JSON for a totally separate project: EES_test!

If you want, I'll send you some screenshots.

Michael



________________________________
From: Khensa Amani Daoudi ***@***.***>
Sent: Thursday, March 7, 2024 4:43 AM
To: Arborator/arborator-frontend ***@***.***>
Cc: Gasser, Michael Edward ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [Arborator/arborator-frontend] [Bug]: adding features to annotation setting (Issue #357)


This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


Hello @megasser<https://github.com/megasser>, I can't reproduce your issue the new feature is succefully added and saved in the 6th column. I have checked your project the feature appears in the feats dialog
Capture.d.ecran.du.2024-03-07.13-41-48.png (view on web)<https://github.com/Arborator/arborator-frontend/assets/50585493/289e3215-20d6-4cb1-b041-2040396d2a31>

**Comment by bguil** [comment]
Hi @megasser,
I think the issue you mention about col6 VS col10 is due to our architecture. When you are working in your project, the data is stored in server memory and then it is stored on disc in a sightly different way.
This means that, when you return to your project a few times after you have closed your session, the location of feats (col6 VS col10) may have changed.

This is something I need to fix in the Grew backend. Sorry for the inconvenience. I will try to fix this in the next few days and post a new comment here when is is fixed.

**Comment by bguil** [comment]
Hi @megasser,

The problem should be fixed and features are stored in the right column according to the config.
Please note that in your project, only `AccNum` is defined as a `FEATS` features.

If you change the config of your project (adding `AccGen` and `AccPers` in the `FEATS` section, the data will be updated accordignly.

**Comment by megasser** [comment]
I'm still having the same problems. The feature I added previously, AccNum, was still not showing up in FEATS in the Settings, so I added it along with others (as follows) to FEATS and saved them. However, they still do not show up in the Settings. And all three of these features are still in column 10 of the CoNLL-U. See attached figure.
       {
            "name": "AccNum",
            "values": [
                "Sing",
                "Plur"
            ]
        },
       {
            "name": "AccGen",
            "values": [
                "Fem",
                "Masc"
            ]
        },
       {
            "name": "AccPers",
            "values": [
                "1",
                "2",
                "3"
            ]
        },
________________________________
From: Bruno Guillaume ***@***.***>
Sent: Monday, March 18, 2024 6:46 AM
To: Arborator/arborator-frontend ***@***.***>
Cc: Gasser, Michael Edward ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [Arborator/arborator-frontend] [Bug]: adding features to annotation setting (Issue #357)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


Hi @megasser<https://github.com/megasser>,

The problem should be fixed and features are stored in the right column according to the config.
Please note that in your project, only AccNum is defined as a FEATS features.

If you change the config of your project (adding AccGen and AccPers in the FEATS section, the data will be updated accordignly.

**Comment by bguil** [comment]
I don't see the feature "AccNum", "AccGen" and "AccPers" in the config of your projet. Please make sure that you have save your config. See button "Save Annotation settings"
<img width="1854" alt="Screenshot 2024-03-21 at 10 16 22" src="https://github.com/Arborator/arborator-frontend/assets/687155/6d435cfc-e950-4d7e-a942-02e9933b18b3">


I've created a new project and uploaded one of your sentence. By default, the new features go to MISC:
<img width="2005" alt="Screenshot 2024-03-21 at 10 12 36" src="https://github.com/Arborator/arborator-frontend/assets/687155/10faa5a5-e77b-44cb-9cec-45884934cb5e">

Then I changed the config, adding the lines of the previous message (defining "AccNum", "AccGen" and "AccPers" in FEATS). 
After, I had to force reload the page and then the features are in the FEATS columns:
<img width="2009" alt="Screenshot 2024-03-21 at 10 13 56" src="https://github.com/Arborator/arborator-frontend/assets/687155/2ba41a94-715a-4455-8227-3ab687beda65">

**Comment by megasser** [comment]
No, as I said, those features do not appear under FEATS in the configuration even though I added them and saved annotation settings (multiple times actually).

I will try this again – I haven't had time yet – but you haven't told me anything that I haven't tried already. Except to start over with a completely new project.

I think the problems I'm having (seemingly almost random behavior; I haven't had time to describe all of the different permutations) may be related to what you described in your previous message: "When you are working in your project, the data is stored in server memory and then it is stored on disc in a slightly different way."

Michael

________________________________
From: Bruno Guillaume ***@***.***>
Sent: Monday, March 18, 2024 6:46 AM
To: Arborator/arborator-frontend ***@***.***>
Cc: Gasser, Michael Edward ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [Arborator/arborator-frontend] [Bug]: adding features to annotation setting (Issue #357)


This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


Hi @megasser<https://github.com/megasser>,

The problem should be fixed and features are stored in the right column according to the config.
Please note that in your project, only AccNum is defined as a FEATS features.

If you change the config of your project (adding AccGen and AccPers in the FEATS section, the data will be updated accordignly.

**Comment by megasser** [comment]
For whatever reason, I'm having more luck with a newly uploaded set of sentences (am_ref1) within the same project (EETB: Amharic). The added features now appear in the right column (6), though they still do not appear under FEATS in the configuration. (Neither do they appear there in the new project that you created using one of our sentences, issue_357.) But not seeing them under FEATS is only a minor problem, as long as they appear in the correct CoNNL-U column.
Thank you.
Michael
________________________________
