### ISSUE TITLE
Empty line missing at the end of Conllu files in export.

### ISSUE THREAD

**Issue by bguil** [Arborator/arborator-frontend#54]
The Conll-U format requires that there is an empty line at the end of each file, after the last sentence (this is useful because with it, the concatenation of 2 Conll-U file remains a valid Conll-U file!)

This empty line is missing in the export files produced by ArboratorGrew.

**Comment by kirianguiller** [comment]
Thanks. It was fixed in a earlier commits

**Comment by bguil** [comment]
I've just test a new export. The problem seems to be still present.
