### ISSUE TITLE
Multi-word tokens

### ISSUE THREAD

**Issue by bguil** [Arborator/arborator-frontend#59]
When importing and then exporting the file:

```
# sent_id = n01018040
# text = Le programme gagne de l'argent grâce au parrainage et à la publicité.
# text_en = The scheme makes money through sponsorship and advertising.
1       Le      le      DET     DT      Gender=Masc|Number=Sing 2       det     _       wordform=le
2       programme       programme       NOUN    NN      Gender=Masc|Number=Sing 3       nsubj   _       _
3       gagne   gagner  VERB    VBC     Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin   0       root    _       _
4       de      un      DET     DT      Gender=Masc|Number=Sing 6       det     _       _
5       l'      le      DET     DT      Gender=Masc|Number=Sing 6       det     _       SpaceAfter=No
6       argent  argent  NOUN    NN      Gender=Masc|Number=Sing 3       obj     _       _
7       grâce   grâce   NOUN    NN      Gender=Fem|Number=Sing  10      case    _       _
8-9     au      _       _       _       _       _       _       _       _
8       à       à       ADP     INDT    _       7       fixed   _       _
9       le      le      DET     _       Gender=Masc|Number=Sing 10      det     _       _
10      parrainage      parrainage      NOUN    NN      Gender=Masc|Number=Sing 3       obl     _       _
11      et      et      CCONJ   CC      _       14      cc      _       _
12      à       à       ADP     IN      _       14      case    _       _
13      la      le      DET     DT      Gender=Fem|Number=Sing  14      det     _       _
14      publicité       publicité       NOUN    NN      Gender=Fem|Number=Sing  10      conj    _       SpaceAfter=No
15      .       .       PUNCT   .       _       3       punct   _       _

```

the multi-word token `8-9     au` is lost.

The problem seems to be on arborator side, because if I upload the file through a grew-server request directly, the mutli-word token is not lost.

**Comment by vistamou** [comment]
Hello, I have the same issue when **downloading** annotator's file, the multiword token sequence information is lost

**Comment by kirianguiller** [comment]
Hello everyone, thanks for your remarks. I fixed the issue earlier in this week. I am closing the issue :).

**Comment by bguil** [comment]
There is still a problem with Multi-word tokens.

I've just run a test, uploading the file below into `Test_bruno`. Just after the uload, the data stored in the Grew back-end does not contains the two MWT `3-4` and `13-14`. It seems that they are removed on ArbotarorGrew side.

```
# sent_id = fr-ud-dev_00048
# text = Le culte du roi est un élément essentiel dans la mobilisation des masses marocaines.
1	Le	le	DET	_	Definite=Def|Gender=Masc|Number=Sing|PronType=Art	2	det	_	wordform=le
2	culte	culte	NOUN	_	Gender=Masc|Number=Sing	6	subj	_	_
3-4	du	_	_	_	_	_	_	_	_
3	de	de	ADP	_	_	2	udep	_	_
4	le	le	DET	_	Definite=Def|Gender=Masc|Number=Sing|PronType=Art	5	det	_	_
5	roi	roi	NOUN	_	Gender=Masc|Number=Sing	3	comp:obj	_	_
6	est	être	AUX	_	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	0	root	_	_
7	un	un	DET	_	Definite=Ind|Gender=Masc|Number=Sing|PronType=Art	8	det	_	_
8	élément	élément	NOUN	_	Gender=Masc|Number=Sing	6	comp:pred	_	_
9	essentiel	essentiel	ADJ	_	Gender=Masc|Number=Sing	8	mod	_	_
10	dans	dans	ADP	_	_	9	mod	_	_
11	la	le	DET	_	Definite=Def|Gender=Fem|Number=Sing|PronType=Art	12	det	_	_
12	mobilisation	mobilisation	NOUN	_	Gender=Fem|Number=Sing	10	comp:obj	_	_
13-14	des	_	_	_	_	_	_	_	_
13	de	de	ADP	_	_	12	udep	_	_
14	les	le	DET	_	Definite=Def|Number=Plur|PronType=Art	15	det	_	_
15	masses	masse	NOUN	_	Gender=Fem|Number=Plur	13	comp:obj	_	_
16	marocaines	marocain	ADJ	_	Gender=Fem|Number=Plur	15	mod	_	SpaceAfter=No
17	.	.	PUNCT	_	_	6	punct	_	_

```

**Comment by bguil** [comment]
Note: the file saved by the flask backend in the local folder `app/tmp/data` has already lost the multi-word tokens information.

**Comment by kirianguiller** [comment]
I tried to fix this bug that occur because of an error on the flask backend. Here the commit : https://github.com/Arborator/arborator-backend/commit/c0ba808219b95d0aaf6a9df1f1f5e93b2a4fe3b7

Please tell me if it's better for you.

Thanks :)

**Comment by bguil** [comment]
It works for me locally. Thanks

**Comment by bguil** [comment]
Everything seems to be Ok, I close. Re-open if needed!
